import React, { useState } from 'react';
import { View, Text, StyleSheet, Platform, Dimensions, TouchableOpacity, Pressable } from 'react-native';
import Animated, { FadeInUp, FadeIn } from 'react-native-reanimated';
import { LinearGradient } from 'expo-linear-gradient';
import { ChevronDown, ChevronUp } from 'lucide-react-native';
import LegalPageShell, { GoldDivider, BG_CARD, BG_SECTION_ALT, GOLD, GOLD_DIM, GOLD_BORDER_SUBTLE, GOLD_GLOW, GOLD_BORDER, TEXT_LIGHT, TEXT_DIM, TEXT_MUTED, SERIF, SANS } from './LegalPageShell';

const { width: SW } = Dimensions.get('window');
const isMobile = SW < 768;

const SECTIONS = [
  {
    title: 'Introduction',
    content: 'This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.\n\nThis website ("DA LUXE" / "Platform") is owned and operated by DA LUXE, a company incorporated under the Companies Act, 2013, with its registered office in Mumbai, Maharashtra, India.\n\nBy accessing or using the Platform, you agree to be bound by these Terms & Conditions. If you do not agree, please refrain from using the Platform.',
  },
  {
    title: 'User Agreement & Acceptance',
    content: 'By using this Platform, you confirm that you are at least 18 years of age, or that you are accessing the Platform under the supervision of a parent or legal guardian.\n\nYou agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate.\n\nYour continued use of the Platform constitutes your acceptance of any modifications to these Terms.',
  },
  {
    title: 'Account Responsibility',
    content: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.\n\nYou must notify DA LUXE immediately of any unauthorized use of your account or any other breach of security.\n\nDA LUXE shall not be liable for any loss arising from your failure to comply with this section.',
  },
  {
    title: 'Limitation of Liability',
    content: 'To the maximum extent permitted by applicable law, DA LUXE and its directors, employees, partners, agents, suppliers, or affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages.\n\nThis includes but is not limited to loss of profits, data, use, goodwill, or other intangible losses resulting from your access to or use of (or inability to access or use) the Platform.\n\nIn no event shall DA LUXE\'s total liability exceed the amount paid by you for the transaction giving rise to the claim.',
  },
  {
    title: 'Intellectual Property Rights',
    content: 'All content on this Platform — including but not limited to text, graphics, logos, icons, images, audio clips, digital downloads, and software — is the property of DA LUXE and is protected by Indian and international copyright laws.\n\nThe DA LUXE name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of DA LUXE. You must not use such marks without our prior written permission.\n\nAny unauthorized reproduction, modification, distribution, or republication is strictly prohibited.',
  },
  {
    title: 'Prohibited Activities',
    content: 'You agree not to use the Platform for any unlawful purpose or in any way that could damage, disable, or impair the Platform.\n\nProhibited activities include but are not limited to:\n• Attempting to interfere with the proper working of the Platform\n• Using any automated means (bots, scrapers) to access the Platform\n• Impersonating another person or entity\n• Uploading viruses or malicious code\n• Engaging in any conduct that restricts others from using the Platform\n• Attempting to reverse-engineer any portion of the Platform',
  },
  {
    title: 'Third-Party Links',
    content: 'The Platform may contain links to third-party websites or services that are not owned or controlled by DA LUXE.\n\nDA LUXE has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services.\n\nYou acknowledge and agree that DA LUXE shall not be responsible or liable for any damage or loss caused by your use of any such third-party content or services.',
  },
  {
    title: 'Payments & Charges',
    content: 'All prices displayed on the Platform are in Indian Rupees (INR) and are inclusive of applicable taxes unless stated otherwise.\n\nPayments are processed through secure third-party payment gateways (PhonePe/Razorpay). DA LUXE does not store your payment card details.\n\nDA LUXE reserves the right to modify prices at any time without prior notice. However, any changes will not affect orders that have already been confirmed.',
  },
  {
    title: 'Indemnification',
    content: 'You agree to defend, indemnify, and hold harmless DA LUXE and its licensees, employees, contractors, agents, officers, and directors from and against any claims, damages, obligations, losses, liabilities, costs, or debt arising from:\n\n• Your use of and access to the Platform\n• Your violation of any term of these Terms & Conditions\n• Your violation of any third-party right\n• Any claim that your content caused damage to a third party',
  },
  {
    title: 'Force Majeure',
    content: 'DA LUXE shall not be liable for any failure to perform its obligations where such failure results from circumstances beyond its reasonable control, including but not limited to natural disasters, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, epidemics, pandemics, or internet disruptions.',
  },
  {
    title: 'Governing Law',
    content: 'These Terms & Conditions shall be governed by and construed in accordance with the laws of India.\n\nAny disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Mumbai, Maharashtra, India.\n\nIf any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.',
  },
  {
    title: 'Contact Information',
    content: 'For any questions or concerns regarding these Terms & Conditions, please contact us:\n\nDA LUXE\nEmail: mydaluxe@gmail.com\nPhone: +91 8879621636\nAddress: Near by - Tasmia medical, mahim east mumbai 400017\n\nWe aim to respond to all inquiries within 24–48 business hours.',
  },
];

const AccordionItem = ({ item, index }: { item: typeof SECTIONS[0]; index: number }) => {
  const [open, setOpen] = useState(index === 0);
  return (
    <Animated.View entering={FadeInUp.delay(100 + index * 60).duration(500)} style={t.accordionItem}>
      <Pressable onPress={() => setOpen(!open)} style={({ pressed }: { pressed: boolean }) => [t.accordionHeader, pressed && { opacity: 0.8 }]}>
        <View style={t.accordionNum}>
          <Text style={t.accordionNumText}>{String(index + 1).padStart(2, '0')}</Text>
        </View>
        <Text style={t.accordionTitle}>{item.title}</Text>
        {open ? <ChevronUp color={GOLD} size={18} /> : <ChevronDown color={TEXT_MUTED} size={18} />}
      </Pressable>
      {open && (
        <Animated.View entering={FadeIn.duration(300)} style={t.accordionBody}>
          <LinearGradient colors={['transparent', GOLD, 'transparent']} start={{ x: 0, y: 0.5 }} end={{ x: 1, y: 0.5 }} style={{ width: 30, height: 1, marginBottom: 16 }} />
          {item.content.split('\n\n').map((para, i) => (
            <Text key={i} style={[t.bodyText, para.startsWith('•') && t.bulletText]}>
              {para.split('\n').map((line, j) => {
                // Bold key phrases
                const boldPatterns = ['DaLuxe', 'shall not be liable', 'exclusive jurisdiction', 'strictly prohibited', 'Indian Rupees', 'does not store'];
                let text = line;
                if (Platform.OS === 'web') {
                  return <Text key={j}>{line}{j < para.split('\n').length - 1 ? '\n' : ''}</Text>;
                }
                return <Text key={j}>{text}{j < para.split('\n').length - 1 ? '\n' : ''}</Text>;
              })}
            </Text>
          ))}
        </Animated.View>
      )}
    </Animated.View>
  );
};

export default function TermsPage({ onNavigate }: { onNavigate?: (page: string) => void }) {
  return (
    <LegalPageShell
      eyebrow="LEGAL"
      title="Terms & Conditions"
      tagline="Please read these terms carefully before using our platform."
      lastUpdated="April 14, 2026"
      breadcrumb="Terms & Conditions"
      onNavigate={onNavigate}
    >
      <View style={t.contentWrap}>
        <Animated.View entering={FadeInUp.duration(600)} style={t.introCard}>
          <Text style={t.introText}>
            By accessing and using DaLuxe, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions. These terms govern your use of our platform, products, and services.
          </Text>
        </Animated.View>

        <GoldDivider width={40} />

        <View style={t.accordionList}>
          {SECTIONS.map((item, i) => (
            <AccordionItem key={i} item={item} index={i} />
          ))}
        </View>
      </View>
    </LegalPageShell>
  );
}

const t = StyleSheet.create({
  contentWrap: { maxWidth: 800, width: '100%', alignSelf: 'center', paddingHorizontal: isMobile ? 20 : 40, paddingVertical: isMobile ? 20 : 32 } as any,
  introCard: {
    backgroundColor: BG_CARD, borderRadius: 18, borderWidth: 1, borderColor: GOLD_BORDER_SUBTLE,
    padding: isMobile ? 20 : 28,
    ...Platform.select({ web: { backdropFilter: 'blur(16px)', boxShadow: '0 4px 24px rgba(0,0,0,0.04)' } as any }),
  } as any,
  introText: { color: TEXT_DIM, fontSize: 14, lineHeight: 24, fontWeight: '400', textAlign: 'center', ...Platform.select({ web: { fontFamily: SANS } as any }) },
  accordionList: { gap: 12 } as any,
  accordionItem: {
    backgroundColor: BG_CARD, borderRadius: 16, borderWidth: 1, borderColor: GOLD_BORDER_SUBTLE, overflow: 'hidden',
    ...Platform.select({ web: { backdropFilter: 'blur(12px)', transition: 'box-shadow 0.3s ease', boxShadow: '0 2px 12px rgba(0,0,0,0.03)' } as any }),
  } as any,
  accordionHeader: {
    flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 18, paddingHorizontal: isMobile ? 16 : 22,
    ...Platform.select({ web: { cursor: 'pointer' } as any }),
  } as any,
  accordionNum: {
    width: 32, height: 32, borderRadius: 16, backgroundColor: GOLD_GLOW, borderWidth: 1, borderColor: GOLD_BORDER,
    justifyContent: 'center', alignItems: 'center',
  } as any,
  accordionNumText: { color: GOLD_DIM, fontSize: 11, fontWeight: '700', letterSpacing: 1, ...Platform.select({ web: { fontFamily: SANS } as any }) },
  accordionTitle: { flex: 1, color: TEXT_LIGHT, fontSize: 14, fontWeight: '600', letterSpacing: 0.5, ...Platform.select({ web: { fontFamily: SANS } as any }) },
  accordionBody: { paddingHorizontal: isMobile ? 16 : 22, paddingBottom: 20, paddingTop: 4 },
  bodyText: { color: TEXT_DIM, fontSize: 13, lineHeight: 22, fontWeight: '400', marginBottom: 12, ...Platform.select({ web: { fontFamily: SANS } as any }) },
  bulletText: { paddingLeft: 8 },
});
